import type { Locale } from "@/src/i18n";

const copy = {
  en: {
    portal: "Admin academic portal",
    dashboard: "Dashboard",
    participants: "Participants",
    assessments: "Assessments",
    analytics: "Scenario Analytics",
    importExport: "Import / Export",
    settings: "Settings",
    logout: "Logout",
    signedIn: "Signed in as {name}",
    secure: "Private administrator session",
    dashboardTitle: "Administration dashboard",
    dashboardIntro:
      "Live participant and assessment records. Analytics and data transfer remain unavailable until their planned phases.",
    totalParticipants: "Total participants",
    completedAssessments: "Completed assessments",
    activeAttempts: "Incomplete attempts",
    recentAssessments: "Recent assessments",
    viewAll: "View all",
    participantsTitle: "Participant records",
    participantsIntro:
      "One row per participant. Score and risk come from that participant's most recently completed attempt by completion time.",
    assessmentsTitle: "Assessment attempts",
    assessmentsIntro:
      "One row per attempt. Incomplete attempts never receive a score or risk label.",
    searchParticipants: "Search name, username, or participant ID",
    searchAssessments: "Search participant, participant ID, or attempt ID",
    search: "Search",
    clear: "Clear",
    accountType: "Account type",
    allTypes: "All account types",
    registered: "Registered",
    anonymous: "Anonymous",
    imported: "Imported",
    risk: "Risk",
    allRisks: "All risk levels",
    low: "Low risk",
    medium: "Medium risk",
    high: "High risk",
    completion: "Completion",
    allStatuses: "All statuses",
    completed: "Completed",
    incomplete: "Incomplete",
    status: "Status",
    source: "Source",
    allSources: "All sources",
    website: "Website",
    googleForm: "Google Form import",
    sort: "Sort",
    newest: "Newest",
    oldest: "Oldest",
    highestScore: "Highest score",
    lowestScore: "Lowest score",
    participant: "Participant",
    participantId: "Participant ID",
    username: "Username",
    latestScore: "Latest score",
    latestSubmission: "Latest submission",
    rawScore: "Raw score",
    submitted: "Submitted",
    started: "Started",
    updated: "Updated",
    created: "Created",
    viewDetails: "View details",
    noRecords: "No records match these filters.",
    unavailable: "Not available",
    page: "Page {page} of {pages}",
    previous: "Previous",
    next: "Next",
    showing: "Showing {from}–{to} of {total}",
    participantDetails: "Participant details",
    assessmentDetails: "Assessment details",
    identity: "Identity information",
    attemptHistory: "Attempt history",
    attempts: "Attempts",
    attemptId: "Attempt ID",
    selectedResponses: "Selected responses",
    scenario: "Scenario {number}",
    selectedAnswer: "Selected answer",
    scoreDelta: "Phase 5 score delta",
    finalScore: "Final raw score",
    completedAt: "Completion time",
    inProgress: "In progress",
    abandoned: "Abandoned",
    excluded: "Excluded",
    noSavedResponses: "No saved responses are available for this attempt.",
    incompleteNotice:
      "This attempt is incomplete, so no score or risk level has been assigned.",
    analyticsTitle: "Scenario analytics",
    analyticsText:
      "Scenario charts and aggregate analytics are planned for Phase 7. No placeholder metrics are shown here.",
    importTitle: "Import / Export",
    importText:
      "CSV import and export are planned for Phase 8. Existing import audit records are read-only in this phase.",
    importAudit: "Import audit records",
    filename: "Filename",
    importState: "State",
    rows: "Rows",
    accepted: "Accepted",
    rejected: "Excluded",
    duplicates: "Duplicates",
    committedAt: "Committed",
    noImports: "No import audit records exist yet.",
    settingsTitle: "Settings",
    settingsIntro:
      "Change the current administrator password. This revokes older sessions and rotates this browser to a new session.",
    passwordRequiredTitle: "Password change required",
    passwordRequiredText:
      "This account is using a temporary bootstrap credential. Change it before accessing administration data.",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    passwordRule:
      "Use 12–128 characters and do not reuse the temporary bootstrap password.",
    changePassword: "Change password",
    changingPassword: "Changing password…",
    passwordChanged:
      "Password changed. Your administrator session was rotated.",
    passwordMismatch: "The new passwords do not match.",
    currentPasswordWrong: "The current password is incorrect.",
    invalidPassword: "Use a new password that meets the stated requirements.",
    requestFailed: "The request could not be completed. Please try again.",
  },
  ar: {
    portal: "بوابة الإدارة الأكاديمية",
    dashboard: "لوحة التحكم",
    participants: "المشاركون",
    assessments: "التقييمات",
    analytics: "تحليلات السيناريوهات",
    importExport: "الاستيراد / التصدير",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    signedIn: "تم تسجيل الدخول باسم {name}",
    secure: "جلسة مسؤول خاصة",
    dashboardTitle: "لوحة تحكم الإدارة",
    dashboardIntro:
      "سجلات المشاركين والتقييمات الفعلية. تبقى التحليلات ونقل البيانات غير متاحة حتى مراحلهما المخططة.",
    totalParticipants: "إجمالي المشاركين",
    completedAssessments: "التقييمات المكتملة",
    activeAttempts: "المحاولات غير المكتملة",
    recentAssessments: "أحدث التقييمات",
    viewAll: "عرض الكل",
    participantsTitle: "سجلات المشاركين",
    participantsIntro:
      "صف واحد لكل مشارك. تأتي الدرجة والمخاطر من أحدث محاولة مكتملة حسب وقت الإكمال.",
    assessmentsTitle: "محاولات التقييم",
    assessmentsIntro:
      "صف واحد لكل محاولة. لا تُمنح المحاولات غير المكتملة درجة أو مستوى مخاطر.",
    searchParticipants: "البحث بالاسم أو اسم المستخدم أو رقم المشارك",
    searchAssessments: "البحث بالمشارك أو رقمه أو رقم المحاولة",
    search: "بحث",
    clear: "مسح",
    accountType: "نوع الحساب",
    allTypes: "كل أنواع الحسابات",
    registered: "مسجل",
    anonymous: "مجهول",
    imported: "مستورد",
    risk: "المخاطر",
    allRisks: "كل مستويات المخاطر",
    low: "مخاطر منخفضة",
    medium: "مخاطر متوسطة",
    high: "مخاطر مرتفعة",
    completion: "الإكمال",
    allStatuses: "كل الحالات",
    completed: "مكتمل",
    incomplete: "غير مكتمل",
    status: "الحالة",
    source: "المصدر",
    allSources: "كل المصادر",
    website: "الموقع الإلكتروني",
    googleForm: "استيراد نموذج Google",
    sort: "الترتيب",
    newest: "الأحدث",
    oldest: "الأقدم",
    highestScore: "أعلى درجة",
    lowestScore: "أدنى درجة",
    participant: "المشارك",
    participantId: "رقم المشارك",
    username: "اسم المستخدم",
    latestScore: "أحدث درجة",
    latestSubmission: "أحدث إرسال",
    rawScore: "الدرجة الخام",
    submitted: "وقت الإرسال",
    started: "وقت البدء",
    updated: "آخر تحديث",
    created: "تاريخ الإنشاء",
    viewDetails: "عرض التفاصيل",
    noRecords: "لا توجد سجلات مطابقة لهذه المرشحات.",
    unavailable: "غير متاح",
    page: "الصفحة {page} من {pages}",
    previous: "السابق",
    next: "التالي",
    showing: "عرض {from}–{to} من {total}",
    participantDetails: "تفاصيل المشارك",
    assessmentDetails: "تفاصيل التقييم",
    identity: "معلومات الهوية",
    attemptHistory: "سجل المحاولات",
    attempts: "المحاولات",
    attemptId: "رقم المحاولة",
    selectedResponses: "الإجابات المختارة",
    scenario: "السيناريو {number}",
    selectedAnswer: "الإجابة المختارة",
    scoreDelta: "فرق درجة المرحلة الخامسة",
    finalScore: "الدرجة الخام النهائية",
    completedAt: "وقت الإكمال",
    inProgress: "قيد التنفيذ",
    abandoned: "متروك",
    excluded: "مستبعد",
    noSavedResponses: "لا توجد إجابات محفوظة لهذه المحاولة.",
    incompleteNotice:
      "هذه المحاولة غير مكتملة، لذلك لم تُمنح درجة أو مستوى مخاطر.",
    analyticsTitle: "تحليلات السيناريوهات",
    analyticsText:
      "الرسوم والتحليلات التجميعية مخططة للمرحلة السابعة. لا تظهر هنا أي مؤشرات مؤقتة.",
    importTitle: "الاستيراد / التصدير",
    importText:
      "استيراد وتصدير CSV مخطط للمرحلة الثامنة. سجلات تدقيق الاستيراد الحالية للقراءة فقط في هذه المرحلة.",
    importAudit: "سجلات تدقيق الاستيراد",
    filename: "اسم الملف",
    importState: "الحالة",
    rows: "الصفوف",
    accepted: "مقبول",
    rejected: "مستبعد",
    duplicates: "مكرر",
    committedAt: "وقت الاعتماد",
    noImports: "لا توجد سجلات تدقيق استيراد حتى الآن.",
    settingsTitle: "الإعدادات",
    settingsIntro:
      "غيّر كلمة مرور المسؤول الحالية. سيؤدي ذلك إلى إلغاء الجلسات القديمة وتدوير جلسة هذا المتصفح.",
    passwordRequiredTitle: "يلزم تغيير كلمة المرور",
    passwordRequiredText:
      "يستخدم هذا الحساب بيانات دخول مؤقتة للتهيئة. غيّرها قبل الوصول إلى بيانات الإدارة.",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور الجديدة",
    passwordRule:
      "استخدم 12–128 حرفًا ولا تُعد استخدام كلمة مرور التهيئة المؤقتة.",
    changePassword: "تغيير كلمة المرور",
    changingPassword: "جارٍ تغيير كلمة المرور…",
    passwordChanged: "تم تغيير كلمة المرور وتدوير جلسة المسؤول.",
    passwordMismatch: "كلمتا المرور الجديدتان غير متطابقتين.",
    currentPasswordWrong: "كلمة المرور الحالية غير صحيحة.",
    invalidPassword: "استخدم كلمة مرور جديدة تستوفي المتطلبات المذكورة.",
    requestFailed: "تعذر إكمال الطلب. حاول مرة أخرى.",
  },
} as const;

export function getAdminCopy(locale: Locale) {
  return copy[locale];
}
