import type { Locale } from "@/src/i18n";

const copy = {
  en: {
    portal: "Admin academic portal",
    dashboard: "Dashboard",
    participants: "Participants",
    assessments: "Assessments",
    analytics: "Scenario Analytics",
    importExport: "Import / Export",
    settings: "Settings",
    logout: "Logout",
    signedIn: "Signed in as {name}",
    secure: "Private administrator session",
    dashboardTitle: "Administration dashboard",
    dashboardIntro:
      "Live, consent-aware participant and assessment analytics from the research database.",
    totalParticipants: "Total participants",
    registeredUsers: "Registered users",
    anonymousParticipants: "Anonymous participants",
    completedAssessments: "Completed assessments",
    averageScore: "Average score",
    lowRiskPercent: "Low risk %",
    mediumRiskPercent: "Medium risk %",
    highRiskPercent: "High risk %",
    activeAttempts: "Incomplete attempts",
    recentAssessments: "Recent assessments",
    riskDistribution: "Risk distribution",
    accountDistribution: "Registered vs anonymous",
    uniqueParticipants: "unique participants",
    eligibleAttempts: "eligible attempts",
    classifiedParticipants: "classified participants",
    analyticsSource: "Analytics source",
    combinedResults: "Combined results",
    websiteAssessments: "Website assessments",
    googleFormAssessments: "Imported Google Form assessments",
    applyFilter: "Apply filter",
    activeSource: "Active source: {source}",
    participantScope:
      "Participant totals count unique participants associated with this source, including those without a completed assessment.",
    assessmentScope:
      "Assessment metrics use consented, completed attempts. Repeat attempts can contribute more than one record.",
    versionScope:
      "Score and response metrics use the active content/rubric pair: {version}.",
    detectedVersions: "Eligible scoring versions: {versions}.",
    incompatibleVersions:
      "{count} eligible attempt(s) use another scoring version and are excluded from score, risk, and scenario calculations.",
    noActiveVersion:
      "No active compatible content and rubric version is available for score analytics.",
    importedAccountNote:
      "{count} imported participant(s) are included in total participants but excluded from the registered-versus-anonymous chart.",
    percentageRounding:
      "Percentages are rounded to one decimal, so displayed values may not total exactly 100%.",
    noEligibleAssessments:
      "No consented, completed assessments match this source.",
    noClassifiedParticipants:
      "No registered or anonymous participants match this source.",
    rawScoreUnit: "raw score",
    viewAll: "View all",
    participantsTitle: "Participant records",
    participantsIntro:
      "One row per participant. Score and risk come from that participant's most recently completed attempt by completion time.",
    assessmentsTitle: "Assessment attempts",
    assessmentsIntro:
      "One row per attempt. Incomplete attempts never receive a score or risk label.",
    searchParticipants: "Search name, username, or participant ID",
    searchAssessments: "Search participant, participant ID, or attempt ID",
    search: "Search",
    clear: "Clear",
    accountType: "Account type",
    allTypes: "All account types",
    registered: "Registered",
    anonymous: "Anonymous",
    imported: "Imported",
    risk: "Risk",
    allRisks: "All risk levels",
    low: "Low risk",
    medium: "Medium risk",
    high: "High risk",
    completion: "Completion",
    allStatuses: "All statuses",
    completed: "Completed",
    incomplete: "Incomplete",
    status: "Status",
    source: "Source",
    allSources: "All sources",
    website: "Website",
    googleForm: "Google Form import",
    sort: "Sort",
    newest: "Newest",
    oldest: "Oldest",
    highestScore: "Highest score",
    lowestScore: "Lowest score",
    participant: "Participant",
    participantId: "Participant ID",
    username: "Username",
    latestScore: "Latest score",
    latestSubmission: "Latest submission",
    rawScore: "Raw score",
    submitted: "Submitted",
    started: "Started",
    updated: "Updated",
    created: "Created",
    viewDetails: "View details",
    noRecords: "No records match these filters.",
    unavailable: "Not available",
    page: "Page {page} of {pages}",
    previous: "Previous",
    next: "Next",
    showing: "Showing {from}–{to} of {total}",
    participantDetails: "Participant details",
    assessmentDetails: "Assessment details",
    identity: "Identity information",
    attemptHistory: "Attempt history",
    attempts: "Attempts",
    attemptId: "Attempt ID",
    selectedResponses: "Selected responses",
    scenario: "Scenario {number}",
    selectedAnswer: "Selected answer",
    scoreDelta: "Phase 5 score delta",
    finalScore: "Final raw score",
    completedAt: "Completion time",
    inProgress: "In progress",
    abandoned: "Abandoned",
    excluded: "Excluded",
    noSavedResponses: "No saved responses are available for this attempt.",
    incompleteNotice:
      "This attempt is incomplete, so no score or risk level has been assigned.",
    analyticsTitle: "Scenario analytics",
    analyticsText:
      "Response distributions for the eight approved bilingual assessment scenarios.",
    scenarioNumber: "Scenario {number}",
    totalEligibleResponses: "Total eligible responses",
    responseDistribution: "Response distribution",
    option: "Option",
    count: "Count",
    percentage: "Percentage",
    scoreDeltaLabel: "Score delta",
    detailedAnalytics: "View detailed analytics",
    scenarioDetailsTitle: "Scenario {number} analytics",
    backToScenarios: "Back to all scenarios",
    responseDenominator:
      "Denominator: {count} persisted response(s) for this scenario from consented, completed attempts using the active scoring version and selected source.",
    attemptsDenominator:
      "The active scoring scope contains {count} consented, completed attempt(s). A missing persisted response is not fabricated or counted.",
    noScenarioResponses:
      "No eligible responses exist for this scenario and source.",
    importTitle: "Import / Export",
    importText:
      "CSV import and export are planned for Phase 8. Existing import audit records are read-only in this phase.",
    importAudit: "Import audit records",
    filename: "Filename",
    importState: "State",
    rows: "Rows",
    accepted: "Accepted",
    rejected: "Excluded",
    duplicates: "Duplicates",
    committedAt: "Committed",
    noImports: "No import audit records exist yet.",
    settingsTitle: "Settings",
    settingsIntro:
      "Change the current administrator password. This revokes older sessions and rotates this browser to a new session.",
    passwordRequiredTitle: "Password change required",
    passwordRequiredText:
      "This account is using a temporary bootstrap credential. Change it before accessing administration data.",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    passwordRule:
      "Use 12–128 characters and do not reuse the temporary bootstrap password.",
    changePassword: "Change password",
    changingPassword: "Changing password…",
    passwordChanged:
      "Password changed. Your administrator session was rotated.",
    passwordMismatch: "The new passwords do not match.",
    currentPasswordWrong: "The current password is incorrect.",
    invalidPassword: "Use a new password that meets the stated requirements.",
    requestFailed: "The request could not be completed. Please try again.",
  },
  ar: {
    portal: "بوابة الإدارة الأكاديمية",
    dashboard: "لوحة التحكم",
    participants: "المشاركون",
    assessments: "التقييمات",
    analytics: "تحليلات السيناريوهات",
    importExport: "الاستيراد / التصدير",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    signedIn: "تم تسجيل الدخول باسم {name}",
    secure: "جلسة مسؤول خاصة",
    dashboardTitle: "لوحة تحكم الإدارة",
    dashboardIntro:
      "تحليلات مباشرة تراعي الموافقة لسجلات المشاركين والتقييمات في قاعدة بيانات البحث.",
    totalParticipants: "إجمالي المشاركين",
    registeredUsers: "المستخدمون المسجلون",
    anonymousParticipants: "المشاركون المجهولون",
    completedAssessments: "التقييمات المكتملة",
    averageScore: "متوسط الدرجة",
    lowRiskPercent: "نسبة الخطر المنخفض",
    mediumRiskPercent: "نسبة الخطر المتوسط",
    highRiskPercent: "نسبة الخطر المرتفع",
    activeAttempts: "المحاولات غير المكتملة",
    recentAssessments: "أحدث التقييمات",
    riskDistribution: "توزيع مستويات الخطر",
    accountDistribution: "المسجلون مقابل المجهولين",
    uniqueParticipants: "مشاركون فريدون",
    eligibleAttempts: "محاولات مؤهلة",
    classifiedParticipants: "مشاركون مصنفون",
    analyticsSource: "مصدر التحليلات",
    combinedResults: "النتائج المجمعة",
    websiteAssessments: "تقييمات الموقع",
    googleFormAssessments: "تقييمات نموذج Google المستوردة",
    applyFilter: "تطبيق المرشح",
    activeSource: "المصدر النشط: {source}",
    participantScope:
      "تحسب إجماليات المشاركين أشخاصًا فريدين مرتبطين بهذا المصدر، بما في ذلك من ليس لديهم تقييم مكتمل.",
    assessmentScope:
      "تستخدم مؤشرات التقييم المحاولات المكتملة والموافق عليها فقط. قد تساهم المحاولات المتكررة بأكثر من سجل.",
    versionScope:
      "تستخدم مؤشرات الدرجات والاستجابات زوج المحتوى وسلّم الدرجات النشط: {version}.",
    detectedVersions: "إصدارات الدرجات المؤهلة: {versions}.",
    incompatibleVersions:
      "تستخدم {count} محاولة مؤهلة إصدارًا آخر من سلّم الدرجات، ولذلك تستبعد من حسابات الدرجات والمخاطر والسيناريوهات.",
    noActiveVersion:
      "لا يتوفر إصدار نشط ومتوافق للمحتوى وسلّم الدرجات من أجل تحليلات الدرجات.",
    importedAccountNote:
      "يشمل إجمالي المشاركين {count} مشاركًا مستوردًا، لكنهم مستبعدون من مخطط المسجلين مقابل المجهولين.",
    percentageRounding:
      "تُقرب النسب إلى منزلة عشرية واحدة، لذلك قد لا يساوي مجموع القيم المعروضة 100٪ تمامًا.",
    noEligibleAssessments:
      "لا توجد تقييمات مكتملة وموافق عليها تطابق هذا المصدر.",
    noClassifiedParticipants:
      "لا يوجد مشاركون مسجلون أو مجهولون يطابقون هذا المصدر.",
    rawScoreUnit: "درجة خام",
    viewAll: "عرض الكل",
    participantsTitle: "سجلات المشاركين",
    participantsIntro:
      "صف واحد لكل مشارك. تأتي الدرجة والمخاطر من أحدث محاولة مكتملة حسب وقت الإكمال.",
    assessmentsTitle: "محاولات التقييم",
    assessmentsIntro:
      "صف واحد لكل محاولة. لا تُمنح المحاولات غير المكتملة درجة أو مستوى مخاطر.",
    searchParticipants: "البحث بالاسم أو اسم المستخدم أو رقم المشارك",
    searchAssessments: "البحث بالمشارك أو رقمه أو رقم المحاولة",
    search: "بحث",
    clear: "مسح",
    accountType: "نوع الحساب",
    allTypes: "كل أنواع الحسابات",
    registered: "مسجل",
    anonymous: "مجهول",
    imported: "مستورد",
    risk: "المخاطر",
    allRisks: "كل مستويات المخاطر",
    low: "مخاطر منخفضة",
    medium: "مخاطر متوسطة",
    high: "مخاطر مرتفعة",
    completion: "الإكمال",
    allStatuses: "كل الحالات",
    completed: "مكتمل",
    incomplete: "غير مكتمل",
    status: "الحالة",
    source: "المصدر",
    allSources: "كل المصادر",
    website: "الموقع الإلكتروني",
    googleForm: "استيراد نموذج Google",
    sort: "الترتيب",
    newest: "الأحدث",
    oldest: "الأقدم",
    highestScore: "أعلى درجة",
    lowestScore: "أدنى درجة",
    participant: "المشارك",
    participantId: "رقم المشارك",
    username: "اسم المستخدم",
    latestScore: "أحدث درجة",
    latestSubmission: "أحدث إرسال",
    rawScore: "الدرجة الخام",
    submitted: "وقت الإرسال",
    started: "وقت البدء",
    updated: "آخر تحديث",
    created: "تاريخ الإنشاء",
    viewDetails: "عرض التفاصيل",
    noRecords: "لا توجد سجلات مطابقة لهذه المرشحات.",
    unavailable: "غير متاح",
    page: "الصفحة {page} من {pages}",
    previous: "السابق",
    next: "التالي",
    showing: "عرض {from}–{to} من {total}",
    participantDetails: "تفاصيل المشارك",
    assessmentDetails: "تفاصيل التقييم",
    identity: "معلومات الهوية",
    attemptHistory: "سجل المحاولات",
    attempts: "المحاولات",
    attemptId: "رقم المحاولة",
    selectedResponses: "الإجابات المختارة",
    scenario: "السيناريو {number}",
    selectedAnswer: "الإجابة المختارة",
    scoreDelta: "فرق درجة المرحلة الخامسة",
    finalScore: "الدرجة الخام النهائية",
    completedAt: "وقت الإكمال",
    inProgress: "قيد التنفيذ",
    abandoned: "متروك",
    excluded: "مستبعد",
    noSavedResponses: "لا توجد إجابات محفوظة لهذه المحاولة.",
    incompleteNotice:
      "هذه المحاولة غير مكتملة، لذلك لم تُمنح درجة أو مستوى مخاطر.",
    analyticsTitle: "تحليلات السيناريوهات",
    analyticsText:
      "توزيعات الاستجابات للسيناريوهات الثمانية المعتمدة للتقييم ثنائي اللغة.",
    scenarioNumber: "السيناريو {number}",
    totalEligibleResponses: "إجمالي الاستجابات المؤهلة",
    responseDistribution: "توزيع الاستجابات",
    option: "الخيار",
    count: "العدد",
    percentage: "النسبة",
    scoreDeltaLabel: "فرق الدرجة",
    detailedAnalytics: "عرض التحليلات التفصيلية",
    scenarioDetailsTitle: "تحليلات السيناريو {number}",
    backToScenarios: "العودة إلى جميع السيناريوهات",
    responseDenominator:
      "المقام: {count} استجابة محفوظة لهذا السيناريو من محاولات مكتملة وموافق عليها تستخدم إصدار الدرجات النشط والمصدر المحدد.",
    attemptsDenominator:
      "يشمل نطاق الدرجات النشط {count} محاولة مكتملة وموافق عليها. لا تُنشأ استجابة مفقودة ولا تُحتسب.",
    noScenarioResponses: "لا توجد استجابات مؤهلة لهذا السيناريو والمصدر.",
    importTitle: "الاستيراد / التصدير",
    importText:
      "استيراد وتصدير CSV مخطط للمرحلة الثامنة. سجلات تدقيق الاستيراد الحالية للقراءة فقط في هذه المرحلة.",
    importAudit: "سجلات تدقيق الاستيراد",
    filename: "اسم الملف",
    importState: "الحالة",
    rows: "الصفوف",
    accepted: "مقبول",
    rejected: "مستبعد",
    duplicates: "مكرر",
    committedAt: "وقت الاعتماد",
    noImports: "لا توجد سجلات تدقيق استيراد حتى الآن.",
    settingsTitle: "الإعدادات",
    settingsIntro:
      "غيّر كلمة مرور المسؤول الحالية. سيؤدي ذلك إلى إلغاء الجلسات القديمة وتدوير جلسة هذا المتصفح.",
    passwordRequiredTitle: "يلزم تغيير كلمة المرور",
    passwordRequiredText:
      "يستخدم هذا الحساب بيانات دخول مؤقتة للتهيئة. غيّرها قبل الوصول إلى بيانات الإدارة.",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور الجديدة",
    passwordRule:
      "استخدم 12–128 حرفًا ولا تُعد استخدام كلمة مرور التهيئة المؤقتة.",
    changePassword: "تغيير كلمة المرور",
    changingPassword: "جارٍ تغيير كلمة المرور…",
    passwordChanged: "تم تغيير كلمة المرور وتدوير جلسة المسؤول.",
    passwordMismatch: "كلمتا المرور الجديدتان غير متطابقتين.",
    currentPasswordWrong: "كلمة المرور الحالية غير صحيحة.",
    invalidPassword: "استخدم كلمة مرور جديدة تستوفي المتطلبات المذكورة.",
    requestFailed: "تعذر إكمال الطلب. حاول مرة أخرى.",
  },
} as const;

export function getAdminCopy(locale: Locale) {
  return copy[locale];
}
